name: Build recovery Image

on: 
  push:
  release:
    types: [published]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    env:
      VENDOR: motorola
      DEVICE: channel
      ANDROID_ROOT: /home/runner/work/orangefox/

    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Build Environment
      run: |
        sudo apt install aria2 -y
        git clone https://gitlab.com/OrangeFox/misc/scripts
        cd scripts
        sudo bash setup/android_build_env.sh
    - name: Downloading source code
      run: |
        export PATH=~/bin:$PATH
        mkdir -p $ANDROID_ROOT
        cd $ANDROID_ROOT
        repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni -b twrp-10.0 --depth=1
        #repo init --depth=1 -u https://gitlab.com/OrangeFox/Manifest.git -b fox_9.0
        repo sync -j8 -c 
        git clone https://github.com/00p513-dev/twrp32-device_motorola_channel -b main --depth=1  device/motorola/channel
 
    - name: Build recovery
      run: |
        chmod +x build.sh
        bash -x build.sh
      shell: bash

    - name : Upload recovery image
      uses: actions/upload-artifact@master
      with:
        name: Images
        path: /home/runner/work/orangefox/out/target/product/*/*.img
